### PR TITLE
[2] Add button to create codesandbox

### PR DESCRIPTION
**Pull request by edades**
Final result

I have created the button to create a codesandbox next to the button to create a codepen, and I moved the button 'Get permalink' under these two buttons.

I had to install `lz-string` lib to create the hash to create the codesandbox.
Originally I tried to install codesanbox lib to use the function `getParameters` but Vite could not compress correctly this lib and thrown an error.
So I had to replicate this function (getParameters) into our code. the same that is using here:
`import { getParameters } from "codesandbox-import-utils/lib/api/define";`

### CODE REVIEW

**Comment by matias-capeletto** [comment]
This is awesome @edades ! Thanks a lot for the PR. 

I think we will need to do something about lz-string. At 4.6kb, it will increase the app size like 20%... for everybody that is not going to use this exporter, we need to avoid making them pay for it. We could load the library when the user press the button for example using dynamic a `import(...)`. 

We could merge this PR and then do that later, or if you want, you could keep developing this feature here.

**Comment by edades** [comment]
Now I left the buttons in a one-line, I added a title attribute to show a native popover when the user hover the button 'codepen' and 'codesandbox'
new view

and I tried to import dynamically the library, following this https://vueschool.io/articles/vuejs-tutorials/lazy-loading-and-code-splitting-in-vue-js/ but I think that maybe we would have to modify some config files because I'm not sure if babel in the Vite configuration is supporting the dynamic import.

So, I understand that this library is almost unnecessary for the project. I tried to isolate or abstract the specific function from the library but this means practically copy all the library to the project.
And I don't know if you want to have this feature right now or you want to wait for a better implementation (with import dynamics)

**Comment by matias-capeletto** [comment]
Great @edades ! I think we can merge this, and then iterate to make the loading lazy. I will merge this in a few days because we need the repo stable during these next days.

**Comment by matias-capeletto** [comment]
Thanks a lot @edades ! This will be great ❤️

**Pull request merged**
