### PR TITLE
CssCodeAreaName Component is renamed as  CodeAreaName

### PR DESCRIPTION
**Pull request by ranjal007**
I have renamed the CssCodeAreameName with CodeAreaName.

### CODE REVIEW

**Comment by matias-capeletto** [comment]
Hey @ranjal007, the rename part of https://github.com/Leniolabs/layoutit-grid/issues/35, was to be able to use this component not only in CssCodeEditor, but also in HtmlCodeEditor. You need to also update where the component is currently used, and if you want implement the new feature described in the issue.

**Comment by ranjal007** [comment]
@matias-capeletto I have updated it. Can you please review it now.

**Comment by matias-capeletto** [comment]
Hey @ranjal007, could you use the renamed component to implement the feature described in the issue? You need to use it here https://github.com/Leniolabs/layoutit-grid/blob/main/src/components/code/HtmlCodeArea.vue instead of the current { cssAreaName }}, in the same way that is being used in the file you just modified. It will be better if we use this PR to close the issue, since you are not far from finishing it.

**Comment by ranjal007** [comment]
@matias-capeletto I haven't worked with vue alot. So I  would face difficulty while doing that.

**Comment by matias-capeletto** [comment]
Hey @ranjal007, only renaming a file is not enough to merge a PR. But I think you should try it out, it is a good opportunity to learn. You need to use the `CodeAreaName` component in HtmlCodeArea in the same as it is used in CssCodeArea. I will let the PR open for a while in case you want to try.

**Pull request closed without merging**
