### PR TITLE
feat: add service worker

### PR DESCRIPTION
**Pull request by userquin**
@patak-js

The service worker is not registered on development (`vite-plugin-pwa` will omit it, just registers a dummy virtual module that does nothing), so you don't need to worry about it. If you want to test the dist, run `npm run build-serve`. 

This PR also includes (see commits for all changes I made):

- exclude intellij/webstorm stuff from .gitignore
- exclude `public/manifest.json` from `index.html`: `manifest` will be configured from `manifest` entry on `VitePWA` plugin on `vite.config.ts`
- `manifest.json` should be removed: I just keep it if you want to change something on new configuration (just compare both to see the changes)
- added `public/icons/icon-36x36.png` to be used on `src/components/props/BrandLogo.vue`: the width attribute was wrong (`widht`) and since its size is changed from css style to `1em` I reduce the size of the asset).
- added `public/icons/android-icon-512x512.png` for `any maskable` on `pwa manifest`
- the service worker is registered on `src/App.vue` on `onMounted` hook: this can be changed to use dynamic import inside the `onMounted` hook, but lighthouse complains to add a preload for the pwa virtual module.
- added `build-serve` on `package.json` scripts: one command to test the build

### CODE REVIEW

**Comment by userquin** [comment]
imagen

**Comment by patak-js** [comment]
This looks awesome @userquin! Thanks a lot 🙌🏼

**Comment by userquin** [comment]
@patak-js 

**Note** on last commit optimize `index.html`:

I have a problem since I cannot access `css` and `assets` on the plugin I have included on `vite.config.ts`, vite manifest plugin will generate the manifest after `LayouitPlugin`. The problem is that `packages/vite/src/node/plugins/assets.ts` doesn't export `chunkToEmittedCssFileMap` and `chunkToEmittedAssetsMap` and so missing from the bundle (if you find a way to have access, let me know).

The plugin just add a `modulepreload` for the main module and then add the module again: via replacing the module. Finally adds `dynamicImports` with `isDynamicEntry: true` before the main module but after the `modulepreload`.

I have added `esno` as `dev dependency` and enable `build.manifest: true` on `vite.config.ts`, and so you can see what is the output. I have added `scripts/optimizeIndexHtml.ts` to show you what we need to do. You can see the output running `npm run build-with-esno` (I also add this script to `package.json`). The problem with `scripts/optimizeIndexHtml.ts` is that modifies the `index.html` and so the `service worker` is not correct (the hash is not correct).

I renamed `public/manifest.json` to `public/original-manifest.json`, I'm generating the vite `manifest.json` for testing.

As you can see, the solution is not easy: with the plugin there is only a warning, about the css preload hint on lighthouse. I think it is the best result we can achieve.

Another thing I need to review is to move the postcss to its own file and then import on `main.ts`. I think I can add another plugin to make it not blocking, generating somehting like this:
```html
<link
      rel="preload"
      as="style"
      onload="this.onload=null;this.rel='stylesheet'"
      href="/assets/index.bc718dfb.css"
/>
<noscript
  ><link rel="stylesheet" href="/assets/index.bc718dfb.css"
/></noscript>
```

Tomorrow I'll remove `esno dev dependency`, remove `build.manifest: true` from `vite.config.ts`, `build-with-esno` script and `scripts/optimizeIndexHtml.ts` and finally rename `public/original-manifest.json` to `public/manifest.json`.

**Comment by userquin** [comment]
@patak-js 

- added `todo@fix:a11y: #757575` on `src/components/grid/TrackSize.vue`
- fix warnings on build  when using `//` as comments on `css` blocks: replace all matches using `/**/`
- we can move the vite plugin to its own module, right now inlined on `vite.config.ts`
- the plugin will replace the css stylesheet link  with non blocking one, it can be changed to keep original

We need to check docs from `vercel` and `AmazonS3` to see if there is no problem with `manifest.webmanifest`, for example, for `netlify` we need to include this:
```toml
# netlify.toml
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
```

**Comment by userquin** [comment]
@patak-js I have never deployed neither on `vercel` nor on `AmazonS3` so I can't help you much.

I suppose that for `AmazonS3` it will be necessary to include the files with the `.webmanifest` extension:
```ts
filePattern: '**/*.{js,css,png,gif,ico,jpg,map,xml,txt,svg,swf,eot,ttf,woff,woff2,otf,wasm,json,webmanifest}'
```

**Comment by userquin** [comment]
@patak-js For `vercel` there is `headers` option: https://vercel.com/docs/configuration#project/headers

**Review by patak-js — APPROVED** [review]
Thanks for taking care of so many details 💯

**Pull request merged**
